import sgMail from '@sendgrid/mail';

if (process.env.SENDGRID_API_KEY) {
  sgMail.setApiKey(process.env.SENDGRID_API_KEY);
}

interface SendReportEmailParams {
  to: string;
  firstName?: string;
  locale: 'fr' | 'en';
  offerType: 'standard' | 'premium';
  reportUrl: string;
  pdfBuffer?: Buffer;
  sessionId: string;
}

export async function sendReportEmail(params: SendReportEmailParams): Promise<void> {
  const { to, firstName, locale, offerType, reportUrl, pdfBuffer, sessionId } = params;

  const labels = {
    fr: {
      subject: `Votre rapport CoupleCheck est prêt${firstName ? `, ${firstName}` : ''} !`,
      preheader: 'Découvrez votre analyse personnalisée de votre relation',
      headline: `${firstName ? `${firstName}, votre` : 'Votre'} rapport est prêt !`,
      body: 'Nous avons analysé vos réponses et préparé un rapport complet et personnalisé pour vous.',
      cta: 'Télécharger mon rapport PDF',
      premium: 'En tant que membre Premium, votre accès à l\'Agent IA Coach est activé.',
      footer: 'Rapport généré par CoupleCheck. Données confidentielles.',
      unsubscribe: 'Se désabonner',
    },
    en: {
      subject: `Your CoupleCheck report is ready${firstName ? `, ${firstName}` : ''}!`,
      preheader: 'Discover your personalized relationship analysis',
      headline: `${firstName ? `${firstName}, your` : 'Your'} report is ready!`,
      body: 'We\'ve analyzed your answers and prepared a complete, personalized report for you.',
      cta: 'Download my PDF report',
      premium: 'As a Premium member, your AI Coach Agent access is activated.',
      footer: 'Report generated by CoupleCheck. Confidential data.',
      unsubscribe: 'Unsubscribe',
    },
  };

  const l = labels[locale];
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://couplecheck.app';

  const html = `
<!DOCTYPE html>
<html lang="${locale}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${l.subject}</title>
</head>
<body style="margin:0;padding:0;background-color:#F5F2EC;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#F5F2EC;padding:40px 20px;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;">
          <!-- Header -->
          <tr>
            <td style="background-color:#1A1916;padding:28px 40px;border-radius:12px 12px 0 0;text-align:center;">
              <span style="color:#AA2C32;font-size:20px;font-weight:700;letter-spacing:1px;">COUPLECHECK</span>
            </td>
          </tr>
          <!-- Body -->
          <tr>
            <td style="background-color:#FFFFFF;padding:48px 40px;">
              <h1 style="margin:0 0 16px;font-size:28px;font-weight:700;color:#1A1916;line-height:1.2;">${l.headline}</h1>
              <p style="margin:0 0 24px;font-size:16px;color:#5B5C59;line-height:1.6;">${l.body}</p>

              <!-- Score badge -->
              <div style="background-color:#F5F2EC;border-radius:12px;padding:24px;margin:24px 0;text-align:center;">
                <div style="font-size:13px;color:#5B5C59;margin-bottom:8px;text-transform:uppercase;letter-spacing:1px;">${locale === 'fr' ? 'VOTRE RAPPORT EST DISPONIBLE' : 'YOUR REPORT IS AVAILABLE'}</div>
                <div style="font-size:15px;font-weight:600;color:#1A1916;">${locale === 'fr' ? 'Rapport PDF · 15 pages · Plan d\'action 30 jours' : 'PDF Report · 15 pages · 30-day action plan'}</div>
              </div>

              <!-- CTA -->
              <div style="text-align:center;margin:32px 0;">
                <a href="${reportUrl}" style="display:inline-block;background-color:#AA2C32;color:#FFFFFF;font-size:16px;font-weight:600;text-decoration:none;padding:16px 32px;border-radius:10px;">${l.cta}</a>
              </div>

              ${offerType === 'premium' ? `<p style="margin:24px 0 0;padding:16px;background-color:#F0F7F3;border-radius:8px;font-size:14px;color:#2A7A4A;border-left:4px solid #2A7A4A;">${l.premium}</p>` : ''}
            </td>
          </tr>
          <!-- Footer -->
          <tr>
            <td style="background-color:#F5F2EC;padding:24px 40px;border-radius:0 0 12px 12px;text-align:center;">
              <p style="margin:0 0 8px;font-size:12px;color:#9B9896;">${l.footer}</p>
              <a href="${appUrl}/unsubscribe?session=${sessionId}" style="font-size:12px;color:#BCBAB6;text-decoration:underline;">${l.unsubscribe}</a>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;

  const msg: sgMail.MailDataRequired = {
    to,
    from: {
      email: process.env.SENDGRID_FROM_EMAIL || 'hello@couplecheck.app',
      name: 'CoupleCheck',
    },
    subject: l.subject,
    html,
    attachments: pdfBuffer
      ? [
          {
            content: pdfBuffer.toString('base64'),
            filename: locale === 'fr' ? 'rapport-couplecheck.pdf' : 'couplecheck-report.pdf',
            type: 'application/pdf',
            disposition: 'attachment',
          },
        ]
      : undefined,
  };

  await sgMail.send(msg);
}
